trigger/main/default/objects/AccountStatus__c/AccountStatus__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ApexSettings</label>
</CustomObject>

trigger/main/default/objects/Topology__c/Topology__c.object-meta.xml
<CustomObject>
    <label>Topology</label>
    <nameField>
        <displayFormat>TP-{YY}{0}</displayFormat>
        <label>Topology No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Topologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trigger/main/default/15982/objects/Topology__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Topologies</relationshipLabel>
    <relationshipName>Topologies</relationshipName>
    <type>Lookup</type>
</CustomField>

trigger/main/default/classes/OpportunityController.cls
public class OpportunityController {
	public static void updateDeliveryStatus(List<Opportunity> oppList, Map<Id, Opportunity> oldMap)
    {
        for (Opportunity opp : oppList)
        {
            if (opp.IsPrivate && oldMap == null)
            {
                opp.DeliveryInstallationStatus__c = 'Completed';
            }
            else if (opp.IsPrivate & opp.IsPrivate != oldMap.get(opp.Id).isPrivate)
            {
                opp.DeliveryInstallationStatus__c = 'Completed';
            }
            else if (opp.IsPrivate == false && oldMap == null)
            {
                opp.DeliveryInstallationStatus__c = 'Yet to begin';
            }
            else if (opp.IsPrivate == false & opp.IsPrivate != oldMap.get(opp.Id).isPrivate)
            {
                opp.DeliveryInstallationStatus__c = 'Yet to begin';
            }
        }
    }
    
    public static void updateTopologyDescription(List<Topology__c> topoList)
    {
        for (Topology__c topo : topoList)
        {
            if (topo.Opportunity__c == null)
            {
                topo.Description__c = 'NO OPPORTUNITY SELECTED';
            }
            else if (topo.Opportunity__c != null)
            {
                topo.Description__c = 'OPPORTUNITY IS SELECTED.';
            }
        }
    }
    
    public static void AccountStatusNumber(List<AccountStatus__c> accStatus)
    {
        
    }
}